<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Agenda_model extends CI_Model
{

    public $table = 'agenda';
    public $id = 'no_agenda';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('no_agenda,invited_by,judul_agenda,deskripsi_agenda,tempat,tanggal,jam,attenders,status');
        $this->datatables->from('agenda');
        //add this line for join
        //$this->datatables->join('table2', 'agenda.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('agenda/read/$1'),'<i class="fa fa-search fa-xs" aria-hidden="true"></i>')." | ".anchor(site_url('agenda/update/$1'),'<i class="fa fa-pencil fa-xs" aria-hidden="true"></i>')." | ".anchor(site_url('agenda/delete/$1'),'<i class="fa fa-trash-o fa-xs" aria-hidden="true"></i>','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'no_agenda');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('no_agenda', $q);
	$this->db->or_like('invited_by', $q);
	$this->db->or_like('judul_agenda', $q);
	$this->db->or_like('deskripsi_agenda', $q);
	$this->db->or_like('tempat', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('jam', $q);
	$this->db->or_like('attenders', $q);
	$this->db->or_like('status', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('no_agenda', $q);
	$this->db->or_like('invited_by', $q);
	$this->db->or_like('judul_agenda', $q);
	$this->db->or_like('deskripsi_agenda', $q);
	$this->db->or_like('tempat', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('jam', $q);
	$this->db->or_like('attenders', $q);
	$this->db->or_like('status', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Agenda_model.php */
/* Location: ./application/models/Agenda_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-12-16 04:42:22 */
/* http://harviacode.com */