<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Message_board_model extends CI_Model
{

    public $table = 'message_board';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,message,authors');
        $this->datatables->from('message_board');
        //add this line for join
        //$this->datatables->join('table2', 'message_board.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('message_board/read/$1'),'<i class="fa fa-search fa-xs" aria-hidden="true"></i>')." | ".anchor(site_url('message_board/update/$1'),'<i class="fa fa-pencil fa-xs" aria-hidden="true"></i>')." | ".anchor(site_url('message_board/delete/$1'),'<i class="fa fa-trash-o fa-xs" aria-hidden="true"></i>','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('message', $q);
	$this->db->or_like('authors', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('message', $q);
	$this->db->or_like('authors', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Message_board_model.php */
/* Location: ./application/models/Message_board_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-12-09 04:37:19 */
/* http://harviacode.com */