<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Spk_model extends CI_Model
{

    public $table = 'spk';
    public $id = 'no_spk';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('no_spk,nama_client,nama_project,item_project,start_date,due_date,status,last_update_by,last_update_time');
        $this->datatables->from('spk');
        //add this line for join
        //$this->datatables->join('table2', 'spk.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('spk/read/$1'),'<i class="fa fa-search fa-xs" aria-hidden="true"></i>')." | ".anchor(site_url('spk/print_spk/$1'),'<i class="fa fa-print fa-xs" aria-hidden="true"></i>')." | ".anchor(site_url('spk/update/$1'),'<i class="fa fa-pencil fa-xs" aria-hidden="true"></i>')." | ".anchor(site_url('spk/delete/$1'),'<i class="fa fa-trash-o fa-xs" aria-hidden="true"></i>','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'no_spk');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('no_spk', $q);
	$this->db->or_like('nama_client', $q);
	$this->db->or_like('nama_project', $q);
	$this->db->or_like('item_project', $q);
	$this->db->or_like('start_date', $q);
	$this->db->or_like('due_date', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('last_update_by', $q);
	$this->db->or_like('last_update_time', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('no_spk', $q);
	$this->db->or_like('nama_client', $q);
	$this->db->or_like('nama_project', $q);
	$this->db->or_like('item_project', $q);
	$this->db->or_like('start_date', $q);
	$this->db->or_like('due_date', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('last_update_by', $q);
	$this->db->or_like('last_update_time', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Spk_model.php */
/* Location: ./application/models/Spk_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-12-22 09:57:12 */
/* http://harviacode.com */